# -*- coding: utf-8 -*-
"""CNPBL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17F0Sx2gWjIthwCIW8p_KfWUXY6Ka0452
"""

import numpy as np
import matplotlib.pyplot as plt

# User input frequencies
f1 = float(input("Enter frequency for User 1: "))
f2 = float(input("Enter frequency for User 2: "))
f3 = float(input("Enter frequency for User 3: "))

c1 = float(input("Enter carrier frequency 1 (FDM): "))
c2 = float(input("Enter carrier frequency 2 (FDM): "))
c3 = float(input("Enter carrier frequency 3 (FDM): "))

w1 = float(input("Enter optical carrier 1 (WDM): "))
w2 = float(input("Enter optical carrier 2 (WDM): "))
w3 = float(input("Enter optical carrier 3 (WDM): "))

t = np.linspace(0, 1, 500)

sig1 = np.sin(2 * np.pi * f1 * t)
sig2 = np.sin(2 * np.pi * f2 * t)
sig3 = np.sin(2 * np.pi * f3 * t)

plt.figure(figsize=(15, 12))

plt.subplot(3, 1, 1)
plt.title(f"User Signal 1 ({f1} Hz)")
plt.plot(t, sig1)

plt.subplot(3, 1, 2)
plt.title(f"User Signal 2 ({f2} Hz)")
plt.plot(t, sig2)

plt.subplot(3, 1, 3)
plt.title(f"User Signal 3 ({f3} Hz)")
plt.plot(t, sig3)

plt.tight_layout()
plt.show()


slot = len(t) // 3
tdm_signal = np.zeros_like(t)
tdm_signal[:slot] = sig1[:slot]
tdm_signal[slot:2*slot] = sig2[:slot]
tdm_signal[2*slot:3*slot] = sig3[:slot]

plt.figure(figsize=(15, 5))
plt.title("Time Division Multiplexing (TDM)")
plt.plot(t, tdm_signal)
plt.tight_layout()
plt.show()


carrier1 = np.sin(2*np.pi*c1*t)
carrier2 = np.sin(2*np.pi*c2*t)
carrier3 = np.sin(2*np.pi*c3*t)

fdm_signal = sig1 * carrier1 + sig2 * carrier2 + sig3 * carrier3

plt.figure(figsize=(15, 5))
plt.title("Frequency Division Multiplexing (FDM)")
plt.plot(t, fdm_signal)
plt.tight_layout()
plt.show()


wdm_c1 = np.sin(2*np.pi*w1*t)
wdm_c2 = np.sin(2*np.pi*w2*t)
wdm_c3 = np.sin(2*np.pi*w3*t)

wdm_signal = sig1 * wdm_c1 + sig2 * wdm_c2 + sig3 * wdm_c3

plt.figure(figsize=(15, 5))
plt.title("Wavelength Division Multiplexing (WDM)")
plt.plot(t, wdm_signal)
plt.tight_layout()
plt.show()